{% set data = load_setup_py_data() %}

package:
  name: cforest
  version: {{ data.get('version') }}

source:
  path: ../causal-forest

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - numpy>=1.16.0
    - pandas>=0.24
    - numba>=0.12
    - joblib>=0.14.1

about:
  home: https://github.com/timmens/causal-forest
  license: MIT
  license_file: LICENSE
  summary: Algorithm to estimate heterogeneous treatment effects. 
